name: omarei
favicon: null
layout_spectrum: 0.87754
typography_spectrum: 0.35082
title: Omarei
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d6d2ad'
    - '#72445e'
    - '#302826'
    - '#f2f3ee'
    - '#bf8253'
  brandStrength: 0.5625
  lightness: 0.375
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
